### TEST
POST http://103.150.190.170:2340/send-mail
Content-Type: application/json

{
    "process_type": "Email",
    "message_type": "Verification",
    "mail": {
        "to": "bridgenote.23@gmail.com",
        "cc": [],
        "bcc": [],
        "reply-to": "",
        "title": "HALLO",
        "body": "DUNYA 1"
    }
}

### TEST
POST http://localhost:2340/send-mail
Content-Type: application/json

{
    "process_type": "Email",
    "message_type": "Verification",
    "mail": {
        "to": "bridgenote.23@gmail.com",
        "cc": [],
        "bcc": [],
        "reply-to": "",
        "title": "HALLO",
        "body": "DUNYA"
    }
}